services:

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capybaras-nestjs
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  # Serviço de banco de dados MySQL
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: capybaras_db
      MYSQL_USER: nest
      MYSQL_PASSWORD: nestpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
