version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capybaras-nestjs
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://nest:nestpassword@db:3306/capybaras_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lake

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: capybaras_db
      MYSQL_USER: nest
      MYSQL_PASSWORD: nestpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - lake

volumes:
  mysql_data:

networks:
  lake: